kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-pv-claim
  labels:
    app: mongopv
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi