version: "3"

services:
  identifier-reponere:
    container_name: identifier-reponere
    build: identifier-repository
    image: smartapigo/identifier-reponere
    links:
    - mongodb
    depends_on:
    - mongodb
    ports:
    - "8080:8080"

  mongodb:
    container_name: mongodb
    image: mongo
    ports:
    - "27017:27017"
    volumes:
    - ./data:/data/db

