apiVersion: v1
kind: Service
metadata:
  name: action-list
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: action-list
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: action-list
  labels:
    app: action-list
spec:
  replicas: 1
  selector:
    matchLabels:
      app: action-list
  template:
    metadata:
      labels:
        app: action-list
    spec:
      containers:
      - name: action-list
        image: atifdockerventure/action-list:latest
        ports:
        - containerPort: 8080
#      dnsPolicy: ClusterFirst