apiVersion: v1
kind: Service
metadata:
  name: create-project
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: create-project
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: create-project
  labels:
    app: create-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: create-project
  template:
    metadata:
      labels:
        app: create-project
    spec:
      containers:
      - name: create-project
        image: atifdockerventure/create-project:latest
        ports:
        - containerPort: 8080