apiVersion: v1
kind: Service
metadata:
  name: data-setup
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: data-setup
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-setup
  labels:
    app: data-setup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-setup
  template:
    metadata:
      labels:
        app: data-setup
    spec:
      containers:
      - name: data-setup
        image: atifdockerventure/data-setup:latest
        ports:
        - containerPort: 8080