apiVersion: v1
kind: Service
metadata:
  name: test-repository
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: test-repository
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-repository
  labels:
    app: test-repository
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-repository
  template:
    metadata:
      labels:
        app: test-repository
    spec:
      containers:
      - name: test-repository
        image: atifdockerventure/test-repository:latest
        ports:
        - containerPort: 8080