apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /action-list
            backend:
              serviceName: action-list
              servicePort: 8080
          - path: /create-project
            backend:
              serviceName: create-project
              servicePort: 8080
          - path: /identifier-repository
            backend:
              serviceName: identifier-repository
              servicePort: 8080
          - path: /test-repository
            backend:
              serviceName: test-repository
              servicePort: 8080
          - path: /test-config
            backend:
              serviceName: test-config
              servicePort: 8080
          - path: /data-setup
            backend:
              serviceName: data-setup
              servicePort: 8080